api/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^auth/$', 'api.views.auth.main', name='api_auth'),
    url(r'^auth/login/(?P<backend>[^/]+)/$', 'api.views.auth.auth', name='socialauth_begin'),
    url(r'^auth/complete/(?P<backend>[^/]+)/$', 'api.views.auth.complete', name='socialauth_complete'),
    url(r'^auth/disconnect/$', 'api.views.auth.disconnect', name='api_auth_disconnect'),
    url(r'^check-auth/$', 'api.views.auth.check', name='api_check_auth'),
    url(r'^auth/done/$', 'api.views.auth.done', name='api_auth_done'),

    url(r'^ws/trains/$', 'api.views.ws.trains', name='api_ws_trains'),
    url(r'^ws/meds/$', 'api.views.ws.meds', name='api_ws_meds'),
    url(r'^ws/resume/$', 'api.views.ws.resume', name='api_ws_resume'),
    
    url(r'^dose/mark/$', 'api.views.spm.dose_mark', name='api_dose_mark'),
    url(r'^spm/(?P<id>[\d]+)/(?P<ts>[\d]+)/$', 'api.views.spm.show', name='api_spm_show'),
    url(r'^spm/(?P<id>[\d]+)/up/(?P<ts>[\d]+)/$', 'api.views.spm.show_up', name='api_spm_show_up'),
    url(r'^spm/(?P<id>[\d]+)/down/(?P<ts>[\d]+)/$', 'api.views.spm.show_down', name='api_spm_show_down'),
    url(r'^spm/list/$', 'api.views.spm.list', name='api_spm_list'),
    
    url(r'^cycle/list/$', 'api.views.cycle.list', name='api_cycle_list'),
    url(r'^cycle/(?P<num>[\w\d]+)/$', 'api.views.cycle.show', name='api_cycle_show'),
    url(r'^cycle/(?P<num>[\w\d]+)/create-plan/$', 'api.views.cycle.create_plan', name='api_cycle_create_plan'),
    
    url(r'^train/(?P<id>[\d]+)/$', 'api.views.train.show', name='api_train_show'),
    url(r'^train/(?P<id>[\d]+)/record/$', 'api.views.train.record', name='api_train_record'),

    url(r'^plan/(?P<id>[\d]+)/(?P<ts>[\d]+)/$', 'api.views.plan.show', name='api_plan_show'),
    url(r'^plan/(?P<id>[\d]+)/up/(?P<ts>[\d]+)/$', 'api.views.plan.show_up', name='api_plan_show_up'),
    url(r'^plan/(?P<id>[\d]+)/down/(?P<ts>[\d]+)/$', 'api.views.plan.show_down', name='api_plan_show_down'),
    url(r'^plan/list/$', 'api.views.plan.list', name='api_plan_list'),

    url(r'^exercise/list/$', 'api.views.exercise.list', name='api_exercise_list'),
    url(r'^exercise/(?P<id>[\d]+)/$', 'api.views.exercise.show', name='api_exercise_show'),
    
    url(r'^util/converter/$', 'api.views.util.converter', name='api_util_converter'),
    
    url(r'^profile/add-weight/$', 'api.views.user.add_weight', name='api_profile_add_weight'),
    url(r'^profile/weight-stat/$', 'api.views.user.weight_stat', name='api_profile_weight_stat'),
    url(r'^user/(?P<id>[\d]+)/$', 'api.views.user.show', name='api_user_show'),
    url(r'^user/edit/$', 'api.views.user.edit', name='api_user_edit'),

    url(r'^video/list/$', 'api.views.video.video_list', name='api_video_list'),
    url(r'^video/info/$', 'api.views.video.info', name='api_video_info'),
    url(r'^video/save/$', 'api.views.video.save', name='api_video_save'),
    url(r'^video/info/$', 'api.views.video.info', name='api_video_info'),
    url(r'^video/show/$', 'api.views.video.show', name='api_video_show'),
    url(r'^video/delete/$', 'api.views.video.delete', name='api_video_delete'),
    url(r'^video/get_progress/$', 'api.views.video.get_progress', name='api_video_get_progress'),
    url(r'^video/exercise_list/$', 'api.views.video.exercise_list', name='api_video_exercise_list'),

    url(r'^payment/list/$', 'api.views.payment_views.payment_list', name='api_payment_list'),
    url(r'^payment/pay/$', 'api.views.payment_views.pay', name='api_payment_pay'),
    url(r'^payment/done/$', 'api.views.payment_views.done', name='api_payment_done'),

    url(r'^like/toggle/$', 'api.views.like.toggle', name='api_like_toggle'),
    url(r'^like/list/$', 'api.views.like.list', name='api_like_list'),

    # v2
    url(r'^v2/', include('api.v2_urls'))
)

lib/django_summernote/urls.py
from django.conf.urls import patterns, url
from django_summernote.views import editor, upload_attachment

urlpatterns = patterns(
    'django_summernote.views',
    url(r'^editor/(?P<id>.+)/$', editor,
        name='django_summernote-editor'),
    url(r'^upload_attachment/$', upload_attachment,
        name='django_summernote-upload_attachment'),
)

main/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('social_auth.urls')),
    url(r'', include('drugplan.urls')),
    url(r'', include('profile.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^video/', include('videohub.urls')),

    url(r'^$', 'main.views.base.home', name='home'),

    url(r'^stream/$', 'main.views.base.stream', name='stream'),

    url(r'^admin/stat/$', 'main.views.admin.stat', name='admin_stat'),
    url(r'^admin/stat2/$', 'main.views.admin.stat2', name='admin_stat2'),
    url(r'^admin/stat/reg/$', 'main.views.admin.stat_users', {'mode': 'reg'}, name='admin_stat_reg'),
    url(r'^admin/stat/login/$', 'main.views.admin.stat_users', {'mode': 'login'}, name='admin_stat_login'),
    url(r'^admin/stat/online/$', 'main.views.admin.stat_users', {'mode': 'online'}, name='admin_stat_online'),
    url(r'^admin/stat/cycle/$', 'main.views.admin.stat_cycle', name='admin_stat_cycle'),
    url(r'^admin/stat/plan/$', 'main.views.admin.stat_plan', name='admin_stat_plan'),
    url(r'^admin/user/(?P<id>\d+)/$', 'main.views.admin.user', name='admin_user'),
    url(r'^admin/user/(?P<id>\d+)/plans/$', 'main.views.admin.user_plans', name='admin_user_plans'),
    url(r'^admin/user/(?P<id>\d+)/requests/$', 'main.views.admin.user_requests', name='admin_user_requests'),
    
    url(r'^util/warmup/$', 'main.views.util.warmup', name='util_warmup'),
    url(r'^util/maximum/$', 'main.views.util.maximum', name='util_maximum'),
    url(r'^util/norms/$', 'main.views.util.norms', name='util_norms'),
    url(r'^util/converter/$', 'main.views.util.converter', name='util_converter'),
    
    # url(r'^$', 'main.views.cycle.list', name='home'),
    url(r'^about/$', 'main.views.base.about', name='about'),
    url(r'^auth/$', 'main.views.base.auth', name='auth'),
    url(r'^auth/success/$', 'main.views.base.auth_success', name='auth_success'),
    url(r'^logout/$', 'main.views.base.logout_view', name='logout'),

    url(r'^exercise/list/$', 'main.views.exercise.list', name='exercise_list'),
    url(r'^exercise/my/list/$', 'main.views.exercise.private_list', name='exercise_private_list'),
    url(r'^exercise/(?P<id>\d+)/$', 'main.views.exercise.show', name='exercise_show'),

    url(r'^cycle/list/$', 'main.views.cycle.list', name='cycle_list'),
    url(r'^cycle/(?P<num>[\w\d]+)/$', 'main.views.cycle.show', name='cycle'),
    url(r'^cycle/(?P<num>[\w\d]+)/create_plan/$', 'main.views.cycle.create_plan', name='cycle_create_plan'),

    url(r'^plan/list/$', 'main.views.plan.list', name='plan_list'),
    url(r'^plan/create/$', 'main.views.plan.create', name='plan_create'),
    url(r'^plan/(?P<id>\d+)/print/$', 'main.views.plan.plan_print', name='plan_print'),
    

    url(r'^lms-admin/', include(admin.site.urls)),

    url(r'^plan/(?P<id>\d+)/delete/$', 'main.views.plan.delete', name='plan_delete'),
    url(r'^plan/(?P<id>\d+)/$', 'main.views.plan_show.show', name='plan'),
    url(r'^plan/(?P<id>\d+)/edit/$', 'main.views.plan_show.edit'),
    url(r'^plan/(?P<id>\d+)/load/(?P<ts>\d+)/$', 'main.views.plan_show.load'),
    url(r'^plan/(?P<id>\d+)/load/down/(?P<ts>\d+)/$', 'main.views.plan_show.load_down'),
    url(r'^plan/(?P<id>\d+)/load/up/(?P<ts>\d+)/$', 'main.views.plan_show.load_up'),
    url(r'^plan/(?P<id>\d+)/train/save/$', 'main.views.plan_show.train_save'),
    url(r'^plan/(?P<id>\d+)/plots/$', 'main.views.plan_show.plots'),
    url(r'^plan/(?P<id>\d+)/pm/list/(?P<ts>\d+)/$', 'main.views.plan_show.pm_list'),
    url(r'^plan/(?P<id>\d+)/pm/save/(?P<ts>\d+)/$', 'main.views.plan_show.pm_save'),
    url(r'^plan/(?P<id>\d+)/pm/get/(?P<d>\d{2}\.\d{2}\.\d{4})/$', 'main.views.plan_show.pm_get'),
    url(r'^plan/(?P<id>\d+)/exercise/create/$', 'main.views.plan_show.exercise_create'),
    url(r'^plan/(?P<id>\d+)/update/(?P<week_num1>\d+)/(?P<week_num2>\d+)/$', 'main.views.plan_show.update'),
    url(r'^plan/(?P<id>\d+)/train/(?P<train_id>\d+)/delete/$', 'main.views.plan_show.train_delete'),
    url(r'^plan/(?P<id>\d+)/exercises/get/$', 'main.views.plan_show.get_exercises'),
    url(r'^plan/(?P<id>\d+)/exercises/save/$', 'main.views.plan_show.save_exercises'),
    url(r'^plan/(?P<id>\d+)/break/add/(?P<week_num>\d+)/$', 'main.views.plan_show.break_add'),
    url(r'^plan/(?P<id>\d+)/break/del/(?P<week_num>\d+)/$', 'main.views.plan_show.break_del'),

    url(r'^news/(?P<mode>[\w\d\._-]+)/$', 'main.views.base.news', name='news'),
    url(r'^app/android/$', 'main.views.base.android'),
    url(r'^app/ios/$', 'main.views.base.ios')
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

profile/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^profile/edit/$', 'profile.views.edit', name='profile_edit'),
    url(r'^profile/favorite/del/$', 'profile.views.favorite_del', name='profile_favorite_del'),
    url(r'^profile/favorite/add/$', 'profile.views.favorite_add', name='profile_favorite_add'),
    url(r'^profile/favorite/clear/$', 'profile.views.favorite_clear', name='profile_favorite_clear'),
    url(r'^profile/weight-stat/$', 'profile.views.weight_stat', name='profile_weight_stat'),
    url(r'^profile/notifications/$', 'profile.views.notifications', name='profile_notifications'),
    url(ur'^users/$', 'profile.views.user_list', name='user_list'),
    url(ur'^user/(?P<username>[\w\d\._-]+)/$', 'profile.views.info', name='profile_show'),
    url(ur'^user/(?P<username>[\w\d\._-]+)/plan/$', 'profile.views.plan', name='profile_plan'),
    url(ur'^user/(?P<username>[\w\d\._-]+)/spm/$', 'profile.views.spm', name='profile_spm'),
    url(ur'^user/(?P<username>[\w\d\._-]+)/video/$', 'profile.views.video', name='profile_video'),
    url(ur'^user/(?P<username>[\w\d\._-]+)/admin/$', 'profile.views.admin', name='profile_admin'),
)

profile/forms.py
#coding=utf8
import os

from django.core.validators import RegexValidator
from django.conf import settings
from django import forms

import awesome_avatar

from profile.models import USER_GENDER_CHOICE, CustomUser


tzchoices = []
f = open(os.path.join(settings.BASE_DIR, 'data', 'timezones'))
for l in f:
    l = l.split('\t')
    tzchoices.append( (l[0], l[1]) )


class MyAvatarWidget(awesome_avatar.widgets.AvatarWidget):
    def value_from_datadict(self, data, files, name):
        if data and files:
            return super(MyAvatarWidget, self).value_from_datadict(data, files, name)

    def render(self, name, value, attrs=None):
        try:
            return super(MyAvatarWidget, self).render(name, value, attrs)
        except:
            pass


class MyAvatarField(awesome_avatar.forms.AvatarField):
    def to_python(self, data):
        if data:
            return super(MyAvatarField, self).to_python(data)
        return data


class UserEditForm(forms.Form):
    avatar = MyAvatarField(label=u'Аватар', required=False, widget=MyAvatarWidget)
    username = forms.CharField(
        label=u'Имя пользователя',
        min_length=4,
        max_length=30,
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z][a-zA-Z0-9_]+$',
                message=u'Допустимы латинские символы и символ `_`',
                code='invalid_value'
            ),
        ],
        required=True
    )
    first_name = forms.CharField(label=u'Имя', min_length=4, max_length=30)
    last_name = forms.CharField(label=u'Фамилия', min_length=4, max_length=30)
    gender = forms.ChoiceField(label=u'Пол', choices=[('', 'неизвестно')] + USER_GENDER_CHOICE.items())
    timezone = forms.ChoiceField(label=u'Часовой пояс', choices=tzchoices, required=False, initial='Europe/Moscow')
    allpowerlifting = forms.URLField(
        label=u'Страница на AllPowerlifting.com',
        required=False,
        validators=[
            RegexValidator(
                regex=r'^http:\/\/allpowerlifting\.com\/lifters\/[A-Z]{3}\/[^/]+\/$',
                message=u'Неверная ссылка, пример: http://allpowerlifting.com/lifters/RUS/talipov-marsel-68878/',
                code='invalid_value'
            ),
        ]
    )

    def clean(self, *args, **kwargs):
        data = super(UserEditForm, self).clean(*args, **kwargs)
        if 'username' in data:
            data['username'] = data['username'].lower()
            qs = CustomUser.objects \
                .filter(username=data['username']) \
                .exclude(pk=self.user.pk)
            if qs.count() > 0:
                self.add_error('username', u'Пользователь с таким именем пользователя уже сушествует.')
        return data

profile/templates/profile/favorite.html
{% load subdomain_urls %}

<li class="favorite">
  {% if f.type == 'plan' %}
    <a href="{% url 'plan' 'ws' f.obj.id %}" style="padding-right:40px"
       class="favorite-{{ f.type }}-{{ f.id }}" target="_blank">
      <i class="fa fa-table"></i> {{ f.obj.name }}
      <i class="fa fa-trash" style="position:absolute;right:10px;padding-top:3px;"
         onclick="del_favorite('{{ f.type }}', '{{ f.id }}');event.preventDefault();"></i>
    </a>
  {% elif f.type == 'spm' %}
    <a href="{% url 'spm_show' 'ws' f.obj.id %}" style="padding-right:40px"
       class="favorite-{{ f.type }}-{{ f.id }}" target="_blank">
      <i class="fa fa-medkit"></i> {{ f.obj.name }}
      <i class="fa fa-trash" style="position:absolute;right:10px;padding-top:3px;"
         onclick="del_favorite('{{ f.type }}', '{{ f.id }}');event.preventDefault();"></i>
    </a>
  {% endif %}
</li>

profile/templates/profile/like_list.html
{% load my_filters %}
{% load thumbnail %}
{% load subdomain_urls %}

{% for like in likes %}
<div class="col-md-4" style="text-align: center">
  {% thumbnail like.user.get_avatar "100x100" crop="center" as im %}
  <img class="img-circle" src="http://ws.last-man.org{{ im.url }}" width="100" height="100"><br>
  {% endthumbnail %}
  <a style="white-space:nowrap;display:block;text-overflow:ellipsis;overflow:hidden;" href="{% url 'profile_show' 'ws' like.user.username %}">{{ like.user.fullname }}</a>
  {{ like.created_at|my_naturaltime }}
</div>
{% endfor %}

profile/templates/profile/like_list_modal.html
<div class="modal fade" id="modal_like_list" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><i class="fa fa-close"></i></button>
        <h4 class="modal-title">Список пользователей, кому это понравилось</h4>
      </div>
      <div class="modal-body" style="overflow-y:auto;max-height:400px;padding:0px;">
      </div>
      <div class="modal-footer">
        <button class="btn btn-default" class="close" data-dismiss="modal">Закрыть</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

profile/templates/profile/like_widget.html
{% load subdomain_urls %}
{% load thumbnail %}

<span class="like_{{ id }} like-widget">
  <i class="like-icon fa {% if is_active %}fa-heart{% else %}fa-heart-o{% endif %}" onclick="likeToggle('{{ id }}');" style="cursor: pointer;"></i>
  {{ count }}
  <div class="head hide"><a href="javascript:showLikes('{{ id }}')">Понравилось {{ count }} людям</a></div>
  <div class="content hide">
    {% for u in users %}
      {% thumbnail u.avatar "50x50" crop="center" as im %}
      {% spaceless %}
      <a href="{% url 'profile_show' 'ws' u.username %}" title="{{ u.fullname }}">
        <img class="img-circle" src="http://ws.last-man.org{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
      </a>
      {% endspaceless %}
      {% endthumbnail %}
    {% endfor %}
  </div>
</span>

profile/templates/profile/notification_avatar.html
{% load thumbnail %}

<div style="display: block;float: left;position: relative;">
  {% thumbnail user.get_avatar "100x100" crop="center" as im %}
    <img class="avatar img-circle" src="http://ws.last-man.org{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
  {% endthumbnail %}
</div>

profile/templates/profile/notifications.html
{% extends 'main/home.html' %}
{% load my_filters %}
{% load subdomain_urls %}

{% block title %}Уведомления{% endblock %}

{% block scripts %}
  <style>
   .cmeta {
     opacity: 0.6;
   }
  </style>
{% endblock %}

{% block content %}
  {% for n in notifications %}
    <div class="col-md-12 well">
      {% if n.verb == 'forum_thread_answer' %}
        {% include 'profile/notification_avatar.html' with user=n.target.user %}
        <div style="word-wrap: break-word;">
          <div style="padding-left:110px">
            <b><a href="{% url 'profile_show' 'ws' n.target.user.username %}">{{ n.target.user.fullname }}</a></b>
            написал ответ в вашу ветку
            <div onclick="window.location.href='{% url 'forum_thread' 'forum' n.target.thread.id n.target.thread.slug %}'" style="cursor: pointer">
              {{ n.target.content|striptags|truncatechars:200 }}
            </div>
            <div class="cmeta">{{ n.created_at|my_naturaltime }}</div>
          </div>
        </div>
      {% elif n.verb == 'forum_answer' %}
        {% include 'profile/notification_avatar.html' with user=n.target.user %}
        <div style="word-wrap: break-word;">
          <div style="padding-left:110px">
            <b><a href="{% url 'profile_show' 'ws' n.target.user.username %}">{{ n.target.user.fullname }}</a></b> ответил на ваше сообщение
            <div onclick="window.location.href='{% url 'forum_thread' 'forum' n.target.thread.id n.target.thread.slug %}'" style="cursor: pointer">
              {{ n.target.content|striptags|truncatechars:200 }}
            </div>
            <div class="cmeta">{{ n.created_at|my_naturaltime }}</div>
          </div>
        </div>
      {% elif n.verb == 'open_trains' %}
        <div style="word-wrap: break-word;">
          Открыто {{ n.get_data.count }} тренировок для плана <b><a href="{% url 'plan' 'ws' n.target.id %}">{{ n.target.name }}</a></b>
          <div class="cmeta">{{ n.created_at|my_naturaltime }}</div>
        </div>
      {% elif n.verb == 'forum_message_like' %}
        {% include 'profile/notification_avatar.html' with user=n.target.user %}
        <div style="word-wrap: break-word;">
          <div style="padding-left:110px">
            <b><a href="{% url 'profile_show' 'ws' n.target.user.username %}">{{ n.target.user.fullname }}</a></b>
            понравилось ваше сообщение
            <div onclick="window.location.href='{% url 'forum_thread' 'forum' n.target.target.thread.id n.target.target.thread.slug %}'" style="cursor: pointer">
              {{ n.target.target.content|striptags|truncatechars:200 }}
            </div>
            <div class="cmeta">{{ n.created_at|my_naturaltime }}</div>
          </div>
        </div>
      {% else %}
      {% endif %}
    </div>
  {% empty %}
    <div class="col-md-12 well">
      У вас нет уведомлений.
    </div>
  {% endfor %}
{% endblock %}

profile/templates/profile/profile_edit.html
{% extends 'main/home.html' %}
{% load bootstrap3 %}

{% block scripts %}
<script type="text/javascript">
$(document).ready(function(){
  $('#id_timezone').select2();
})
</script>
{% endblock %}

{% block title %}
Редактирование профиля
{% endblock %}

{% block content %}
<div class="col-md-12">
  <h3>Редактирование профиля</h3>
</div>
<div class="col-md-12">
  <div class="well">
    <form method="POST" enctype="multipart/form-data" autocomplete="off">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="form-group pull-right">
        <button type="submit" class="btn btn-success">Сохранить</button>
      </div>
      <div class="clearfix">
      </div>
    </form>
  </div>
</div>
{% endblock %}

profile/templates/profile/rank_with_icon.html
{% load my_filters %}

{% if user.is_banned %}
  <div title="забанен {{ user.banned_at|my_naturaltime }} за {{ user.get_ban_reason }}">
    <i class="fa fa-ban" alt="забанен"></i>
    <small>{{ user.get_rank }}</small>
  </div>
{% elif user.is_moderator%}
  <div title="модератор">
    <i class="fa fa-star"></i>
    <small>{{ user.get_rank }}</small>
  </div>
{% else %}
  <div>
    <small>{{ user.get_rank }}</small>
  </div>
{% endif %}

profile/templates/profile/user_list.html
{% extends 'main/home.html' %}
{% load thumbnail %}
{% load bootstrap3 %}
{% load my_filters %}

{% block title %}Список пользователей{% endblock %}

{% block content %}
<div class="col-md-12">
  {% breadcrumbs_block %}

  <form class="well" method="GET">
    {% bootstrap_form form %}
    <div class="form-group">
      <button type="submit" class="btn btn-default pull-right" name="search">Поиск</button>
    </div>
    <div class="clearfix"></div>
  </form>

  <table class="table table-striped">
    {% for user in list %}
      <tr>
        <td>
          <a href="{% url 'profile_show' user.username %}">
            {% if user.avatar %}
              {% thumbnail user.get_avatar "50x50" crop="center" as im %}
                <img class="avatar img-circle" src="http://ws.last-man.org{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
              {% endthumbnail %}
            {% else %}
              <img class="avatar img-circle" src="/static/img/unknown.jpg" width="50" height="50">
            {% endif %}
          </a>
        </td>
        <td>
          <a href="{% url 'profile_show' user.username %}">
            {{ user.fullname }}
          </a>
        </td>
        <td>
          {% include 'profile/rank_with_icon.html' with user=user %}
        </td>
      </tr>
    {% endfor %}
  </table>
  {% include 'main/pagination.html' %}
</div>
{% endblock %}

profile/templates/profile/weight_stat.html
{% extends 'main/home.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}Статистика веса{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/highcharts/highcharts.js' %}"></script>
<script type="text/javascript" src="{% static 'js/highcharts/exporting.js' %}"></script>
<script type="text/javascript" src="{% static 'js/highcharts/dark-unica.js' %}"></script>
<script type="text/javascript">
Highcharts.setOptions({
            lang: {
                loading: 'Загрузка...',
                months: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
                weekdays: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
                shortMonths: ['Янв', 'Фев', 'Март', 'Апр', 'Май', 'Июнь', 'Июль', 'Авг', 'Сент', 'Окт', 'Нояб', 'Дек'],
                exportButtonTitle: "Экспорт",
                printButtonTitle: "Печать",
                rangeSelectorFrom: "С",
                rangeSelectorTo: "По",
                rangeSelectorZoom: "Период",
                downloadPNG: 'Скачать PNG',
                downloadJPEG: 'Скачать JPEG',
                downloadPDF: 'Скачать PDF',
                downloadSVG: 'Скачать SVG',
                printChart: 'Напечатать график'
            }
    });
$(function () {
    $('#plot').highcharts({
        title: {
            text: 'Вес',
        }, chart: {
            type: 'spline'
        },
        rangeSelector: {
            selected: 1
        },
        xAxis: {
            type: 'datetime',
            
            title: {
                text: 'Дата'
            }
        },
        yAxis: {
            title: {
                text: 'Вес, кг'
            },
            endOnTick: false,
            startOnTick: false
        },
        series: [{
            showInLegend: false,
            data: [
                {% for r in records %}
                [Date.UTC({{ r.date.year }}, {{ r.date.month|add:"-1" }}, {{ r.date.day }}), {{ r.value }}],
                {% endfor %}
            ]
        }]
    });
});
</script>
{% endblock %}

{% block content %}
<div class="col-md-4">
  <form class="well" method="POST">
    <h4>Взвеситься</h4>
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-group">
      <button type="submit" class="btn btn-default pull-right">Сохранить</button>
    </div>
    <div class="clearfix"></div>
  </form>
</div>
<div class="col-md-8">
  {% if records %}
  <div id="plot"></div>
  {% else %}
  <div class="alert alert-danger">Отсутствуют данные о весе. Чтобы добавить используйте форму справа.</div>
  {% endif %}
</div>
{% endblock %}