api/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^auth/$', 'api.views.auth.main', name='api_auth'),
    url(r'^auth/login/(?P<backend>[^/]+)/$', 'api.views.auth.auth', name='socialauth_begin'),
    url(r'^auth/complete/(?P<backend>[^/]+)/$', 'api.views.auth.complete', name='socialauth_complete'),
    url(r'^auth/disconnect/$', 'api.views.auth.disconnect', name='api_auth_disconnect'),
    url(r'^check-auth/$', 'api.views.auth.check', name='api_check_auth'),
    url(r'^auth/done/$', 'api.views.auth.done', name='api_auth_done'),

    url(r'^ws/trains/$', 'api.views.ws.trains', name='api_ws_trains'),
    url(r'^ws/meds/$', 'api.views.ws.meds', name='api_ws_meds'),
    url(r'^ws/resume/$', 'api.views.ws.resume', name='api_ws_resume'),
    
    url(r'^dose/mark/$', 'api.views.spm.dose_mark', name='api_dose_mark'),
    url(r'^spm/(?P<id>[\d]+)/(?P<ts>[\d]+)/$', 'api.views.spm.show', name='api_spm_show'),
    url(r'^spm/(?P<id>[\d]+)/up/(?P<ts>[\d]+)/$', 'api.views.spm.show_up', name='api_spm_show_up'),
    url(r'^spm/(?P<id>[\d]+)/down/(?P<ts>[\d]+)/$', 'api.views.spm.show_down', name='api_spm_show_down'),
    url(r'^spm/list/$', 'api.views.spm.list', name='api_spm_list'),
    
    url(r'^cycle/list/$', 'api.views.cycle.list', name='api_cycle_list'),
    url(r'^cycle/(?P<num>[\w\d]+)/$', 'api.views.cycle.show', name='api_cycle_show'),
    url(r'^cycle/(?P<num>[\w\d]+)/create-plan/$', 'api.views.cycle.create_plan', name='api_cycle_create_plan'),
    
    url(r'^train/(?P<id>[\d]+)/$', 'api.views.train.show', name='api_train_show'),
    url(r'^train/(?P<id>[\d]+)/record/$', 'api.views.train.record', name='api_train_record'),

    url(r'^plan/(?P<id>[\d]+)/(?P<ts>[\d]+)/$', 'api.views.plan.show', name='api_plan_show'),
    url(r'^plan/(?P<id>[\d]+)/up/(?P<ts>[\d]+)/$', 'api.views.plan.show_up', name='api_plan_show_up'),
    url(r'^plan/(?P<id>[\d]+)/down/(?P<ts>[\d]+)/$', 'api.views.plan.show_down', name='api_plan_show_down'),
    url(r'^plan/list/$', 'api.views.plan.list', name='api_plan_list'),

    url(r'^exercise/list/$', 'api.views.exercise.list', name='api_exercise_list'),
    url(r'^exercise/(?P<id>[\d]+)/$', 'api.views.exercise.show', name='api_exercise_show'),
    
    url(r'^util/converter/$', 'api.views.util.converter', name='api_util_converter'),
    
    url(r'^profile/add-weight/$', 'api.views.user.add_weight', name='api_profile_add_weight'),
    url(r'^profile/weight-stat/$', 'api.views.user.weight_stat', name='api_profile_weight_stat'),
    url(r'^user/(?P<id>[\d]+)/$', 'api.views.user.show', name='api_user_show'),
    url(r'^user/edit/$', 'api.views.user.edit', name='api_user_edit'),

    url(r'^video/list/$', 'api.views.video.video_list', name='api_video_list'),
    url(r'^video/info/$', 'api.views.video.info', name='api_video_info'),
    url(r'^video/save/$', 'api.views.video.save', name='api_video_save'),
    url(r'^video/info/$', 'api.views.video.info', name='api_video_info'),
    url(r'^video/show/$', 'api.views.video.show', name='api_video_show'),
    url(r'^video/delete/$', 'api.views.video.delete', name='api_video_delete'),
    url(r'^video/get_progress/$', 'api.views.video.get_progress', name='api_video_get_progress'),
    url(r'^video/exercise_list/$', 'api.views.video.exercise_list', name='api_video_exercise_list'),

    url(r'^payment/list/$', 'api.views.payment_views.payment_list', name='api_payment_list'),
    url(r'^payment/pay/$', 'api.views.payment_views.pay', name='api_payment_pay'),
    url(r'^payment/done/$', 'api.views.payment_views.done', name='api_payment_done'),

    url(r'^like/toggle/$', 'api.views.like.toggle', name='api_like_toggle'),
    url(r'^like/list/$', 'api.views.like.list', name='api_like_list'),

    # v2
    url(r'^v2/', include('api.v2_urls'))
)

lib/django_summernote/urls.py
from django.conf.urls import patterns, url
from django_summernote.views import editor, upload_attachment

urlpatterns = patterns(
    'django_summernote.views',
    url(r'^editor/(?P<id>.+)/$', editor,
        name='django_summernote-editor'),
    url(r'^upload_attachment/$', upload_attachment,
        name='django_summernote-upload_attachment'),
)

main/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('social_auth.urls')),
    url(r'', include('drugplan.urls')),
    url(r'', include('profile.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^video/', include('videohub.urls')),

    url(r'^$', 'main.views.base.home', name='home'),

    url(r'^stream/$', 'main.views.base.stream', name='stream'),

    url(r'^admin/stat/$', 'main.views.admin.stat', name='admin_stat'),
    url(r'^admin/stat2/$', 'main.views.admin.stat2', name='admin_stat2'),
    url(r'^admin/stat/reg/$', 'main.views.admin.stat_users', {'mode': 'reg'}, name='admin_stat_reg'),
    url(r'^admin/stat/login/$', 'main.views.admin.stat_users', {'mode': 'login'}, name='admin_stat_login'),
    url(r'^admin/stat/online/$', 'main.views.admin.stat_users', {'mode': 'online'}, name='admin_stat_online'),
    url(r'^admin/stat/cycle/$', 'main.views.admin.stat_cycle', name='admin_stat_cycle'),
    url(r'^admin/stat/plan/$', 'main.views.admin.stat_plan', name='admin_stat_plan'),
    url(r'^admin/user/(?P<id>\d+)/$', 'main.views.admin.user', name='admin_user'),
    url(r'^admin/user/(?P<id>\d+)/plans/$', 'main.views.admin.user_plans', name='admin_user_plans'),
    url(r'^admin/user/(?P<id>\d+)/requests/$', 'main.views.admin.user_requests', name='admin_user_requests'),
    
    url(r'^util/warmup/$', 'main.views.util.warmup', name='util_warmup'),
    url(r'^util/maximum/$', 'main.views.util.maximum', name='util_maximum'),
    url(r'^util/norms/$', 'main.views.util.norms', name='util_norms'),
    url(r'^util/converter/$', 'main.views.util.converter', name='util_converter'),
    
    # url(r'^$', 'main.views.cycle.list', name='home'),
    url(r'^about/$', 'main.views.base.about', name='about'),
    url(r'^auth/$', 'main.views.base.auth', name='auth'),
    url(r'^auth/success/$', 'main.views.base.auth_success', name='auth_success'),
    url(r'^logout/$', 'main.views.base.logout_view', name='logout'),

    url(r'^exercise/list/$', 'main.views.exercise.list', name='exercise_list'),
    url(r'^exercise/my/list/$', 'main.views.exercise.private_list', name='exercise_private_list'),
    url(r'^exercise/(?P<id>\d+)/$', 'main.views.exercise.show', name='exercise_show'),

    url(r'^cycle/list/$', 'main.views.cycle.list', name='cycle_list'),
    url(r'^cycle/(?P<num>[\w\d]+)/$', 'main.views.cycle.show', name='cycle'),
    url(r'^cycle/(?P<num>[\w\d]+)/create_plan/$', 'main.views.cycle.create_plan', name='cycle_create_plan'),

    url(r'^plan/list/$', 'main.views.plan.list', name='plan_list'),
    url(r'^plan/create/$', 'main.views.plan.create', name='plan_create'),
    url(r'^plan/(?P<id>\d+)/print/$', 'main.views.plan.plan_print', name='plan_print'),
    

    url(r'^lms-admin/', include(admin.site.urls)),

    url(r'^plan/(?P<id>\d+)/delete/$', 'main.views.plan.delete', name='plan_delete'),
    url(r'^plan/(?P<id>\d+)/$', 'main.views.plan_show.show', name='plan'),
    url(r'^plan/(?P<id>\d+)/edit/$', 'main.views.plan_show.edit'),
    url(r'^plan/(?P<id>\d+)/load/(?P<ts>\d+)/$', 'main.views.plan_show.load'),
    url(r'^plan/(?P<id>\d+)/load/down/(?P<ts>\d+)/$', 'main.views.plan_show.load_down'),
    url(r'^plan/(?P<id>\d+)/load/up/(?P<ts>\d+)/$', 'main.views.plan_show.load_up'),
    url(r'^plan/(?P<id>\d+)/train/save/$', 'main.views.plan_show.train_save'),
    url(r'^plan/(?P<id>\d+)/plots/$', 'main.views.plan_show.plots'),
    url(r'^plan/(?P<id>\d+)/pm/list/(?P<ts>\d+)/$', 'main.views.plan_show.pm_list'),
    url(r'^plan/(?P<id>\d+)/pm/save/(?P<ts>\d+)/$', 'main.views.plan_show.pm_save'),
    url(r'^plan/(?P<id>\d+)/pm/get/(?P<d>\d{2}\.\d{2}\.\d{4})/$', 'main.views.plan_show.pm_get'),
    url(r'^plan/(?P<id>\d+)/exercise/create/$', 'main.views.plan_show.exercise_create'),
    url(r'^plan/(?P<id>\d+)/update/(?P<week_num1>\d+)/(?P<week_num2>\d+)/$', 'main.views.plan_show.update'),
    url(r'^plan/(?P<id>\d+)/train/(?P<train_id>\d+)/delete/$', 'main.views.plan_show.train_delete'),
    url(r'^plan/(?P<id>\d+)/exercises/get/$', 'main.views.plan_show.get_exercises'),
    url(r'^plan/(?P<id>\d+)/exercises/save/$', 'main.views.plan_show.save_exercises'),
    url(r'^plan/(?P<id>\d+)/break/add/(?P<week_num>\d+)/$', 'main.views.plan_show.break_add'),
    url(r'^plan/(?P<id>\d+)/break/del/(?P<week_num>\d+)/$', 'main.views.plan_show.break_del'),

    url(r'^news/(?P<mode>[\w\d\._-]+)/$', 'main.views.base.news', name='news'),
    url(r'^app/android/$', 'main.views.base.android'),
    url(r'^app/ios/$', 'main.views.base.ios')
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

videohub/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^(?P<id>\d+)/$', 'videohub.views.show', name='video_show'),
    url(r'^(?P<id>\d+)/delete/$', 'videohub.views.delete', name='video_delete'),
    url(r'^list/$', 'videohub.views.video_list', name='video_list'),
)

videohub/models.py
#coding=utf8


from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from main.models import Exercise, TrainingScheme


class VideoManager(models.Manager):
    def get_active(self):
        return super(VideoManager, self).get_queryset().filter(is_deleted=False, is_uploaded__isnull=False)


class Video(models.Model):
    objects = VideoManager()

    youtube_id = models.TextField(max_length=12)
    hash = models.TextField(max_length=32, null=True, blank=True, default=None)

    #  None - ожидает загрузки, True - видео загружено в канал LMS, False - видео вставленно по ссылке
    is_uploaded = models.NullBooleanField(default=False)
    is_public = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(User, verbose_name=u'Автор')
    executed_at = models.DateField(verbose_name=u'Дата выполнения')

    exercise = models.ForeignKey(Exercise, verbose_name=u'Упражнение', null=True, blank=None, default=None)
    weight = models.FloatField(verbose_name=u'Вес', null=True, blank=None, default=None)
    reps = models.SmallIntegerField(verbose_name=u'Повторения', null=True, blank=None, default=None)
    app = models.SmallIntegerField(verbose_name=u'Номер подхода', null=True, blank=None, default=None)

    scheme = models.ForeignKey(TrainingScheme, verbose_name=u'Выполнение', null=True, blank=True, default=None,
                               on_delete=models.SET_NULL)

    view_count = models.PositiveIntegerField(verbose_name=u'Количество просмотров', default=0)

    def save(self, *args, **kwargs):
        if not self.executed_at:
            self.executed_at = timezone.now().date()
        super(Video, self).save(*args, **kwargs)

    @property
    def name(self):
        res = u'%s %g на %s' % (self.exercise.name, self.weight, self.reps)
        if self.app:
            res += u' (%d подход)' % self.app
        return res

videohub/views.py
#coding=utf8
import tempfile

from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http.response import Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_protect

from common.views import auth_check
from videohub.services.video import VideoService
from videohub.models import Video
from main.models import Exercise


@auth_check(ajax=False)
def video_list(request):
    """
    Личный список видео пользователя
    """
    qs = Video.objects.get_active().filter(user=request.user)
    paginator = Paginator(qs, 50)
    page = request.GET.get('page')
    try:
        objs = paginator.page(page)
    except PageNotAnInteger:
        objs = paginator.page(1)
    except EmptyPage:
        objs = paginator.page(paginator.num_pages)

    return render(request, 'videohub/list.html', {
        'objs': objs,
        'menu': 'video_list',
    })


def show(request, id):
    try:
        video = Video.objects.get_active().get(pk=id)
    except:
        raise Http404()

    if not video.is_public and \
            (not request.user.is_authenticated() or request.user.id != video.user_id):
        raise Http404()

    return render(request, 'videohub/show.html', {
        'video': video,
    })


@csrf_protect
@auth_check(ajax=False)
def delete(request, id):
    try:
        video = Video.objects.get_active().get(pk=id)
    except:
        raise Http404(u'Видео не найдено')

    if request.user.id != video.user_id:
        raise Http404(u'Нет доступа.')

    VideoService.delete_video(video)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('video_list')))

videohub/templates/videohub/add.html
{% extends 'main/home.html' %}
{% load staticfiles %}

{% block title %}Загрузка видео{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js"></script>
  <
  <script type="text/javascript" src="{% static 'js/angular-locale_ru-ru.js' %}"></script>
  <script>

var mainApp = angular.module('mainApp', []).config(function($interpolateProvider) {
  $interpolateProvider.startSymbol('{$');
  $interpolateProvider.endSymbol('$}');
});
mainApp.config(['$httpProvider', function($httpProvider) {
        $httpProvider.defaults.useXDomain = true;
        delete $httpProvider.defaults.headers.common['X-Requested-With'];
    }
]);
mainApp.controller('AddVideoCtrl', function ($scope, $http) {
  $scope.url = '';
  $scope.video = false;
  $scope.setUrl = function () {
    $scope.url = 'https://www.youtube.com/watch?v=WV74FCcGgqg';
    $http.get('http://api.test.last-man.org/video/info/?url=' + $scope.url)
    .success(function(data) {
      console.log('!!!', data);
    });
  }
});
  </script>
{% endblock %}

{% block content %}
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form class="form well" ng-app="mainApp" ng-controller="AddVideoCtrl">

            <div class="form-group" ng-if="video">
              <label>Изображение</label>
              <br>
              <img src="{$ video.preview $}">
            </div>

            <div class="form-group" ng-if="video">
              <label for="link">Название</label>
              <input type="text" class="form-control" ng-model="video.name">
            </div>

            <div class="form-group" ng-if="video">
              <label for="link">Описание</label>
              <textarea class="form-control" ng-model="video.description"></textarea>
            </div>

            <div class="form-group" ng-if="video">
              <label for="link">Публичный доступ</label>
              <input type="checkbox" ng-model="video.is_public">
            </div>

            <div class="form-group" ng-if="!video">
              <label for="link">Ссылка</label>
              <input type="url" class="form-control" name="link" id="link" placeholder="http://" ng-model="url" ng-change="setUrl()">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

videohub/templates/videohub/add_form.html
{% load subdomain_urls %}
<script>
var csrf_token = "{{ csrf_token }}";
</script>

<div class="modal fade" id="video_add_form" ng-app="addVideoApp" ng-controller="AddVideoCtrl"
     tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <form class="form" autocomplete="off">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Закрыть">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" style="text-align:center;">Загрузка видео</h4>
        </div>
        <div class="modal-body">
          <div ng-if="data.state=='select_type'" style="text-align:center">
            <input type="file" onchange="angular.element(this).scope().fileChange(this)" style="display:none;"/>
            <button type="button" class="btn btn-default" onclick="$(this).prev().click();">Выбрать файл</button>
            <div>
              или
            </div>
            <button class="btn btn-default" ng-click="data.state='set_link'">Добавить с другого сайта</button>
          </div>
          <div ng-if="data.state=='set_link'">
            <div class="form-group">
              <label for="link">Ссылка на видеоролик</label>
              <input type="url" class="form-control" name="link" id="link" placeholder="http://"
                     ng-model-options="{ debounce: 1000 }" ng-model="data.url" ng-change="setUrl()">
            </div>
            <div class="form-group" style="text-align:center">
              Вы можете указать ссылку на страницу видеозаписи Youtube.
            </div>
          </div>
          <div ng-if="data.state=='send_form' || data.state=='progress' || data.state=='upload'">
            <div class="col-md-12">
              <div class="form-group" ng-if="data.preview">
                <label>Превью</label>
                <br>
                <img ng-if="data.type=='youtube'" ng-src="{$ data.preview $}"
                     class="img-responsive center-block">
                <video ng-if="data.type=='file'" ng-src="{$ data.preview $}" controls
                     style="max-width:100%;max-height:100%;"></video>
              </div>
            </div>
            <div class="row">
              <div ng-if="!video.scheme_id">
                <div class="form-group col-xs-6">
                  <label>Упражнение</label>
                  <select class="form-control" ng-model="video.exercise_id"
                          select2 ng-disabled="data.state!='send_form'">
                    <option value="{$ e.id $}" ng-repeat="e in exercises" ng-bind="e.name"></option>
                  </select>
                </div>

                <div class="form-group col-xs-6">
                  <label>Дата выполнения</label>
                  <input type="text" class="form-control" ng-model="video.executed_at"
                         ng-disabled="data.state!='send_form'" data-provide="datepicker">
                </div>


                <div class="form-group col-xs-4">
                  <label>Вес снаряда</label>
                  <input type="number" class="form-control" ng-model="video.weight"
                         ng-disabled="data.state!='send_form'">
                </div>

                <div class="form-group col-xs-4">
                  <label>Повторения</label>
                  <input type="number" class="form-control" ng-model="video.reps"
                         ng-disabled="data.state!='send_form'">
                </div>

                <div class="form-group col-xs-4">
                  <label>Номер подхода</label>
                  <input type="number" class="form-control" ng-model="video.app"
                         ng-disabled="data.state!='send_form'">
                </div>

              </div>

              <div class="form-group col-md-12" style="border-top:1px solid #1c1e22;padding-top:5px;">
                <label>Название (необязательно)</label>
                <input type="text" class="form-control" ng-model="video.title" ng-disabled="data.state!='send_form'">
              </div>

              <div class="form-group col-md-12">
                <label>Описание (необязательно)</label>
                <textarea class="form-control" ng-model="video.description"
                          ng-disabled="data.state!='send_form'"></textarea>
              </div>

              <div class="form-group col-md-12">
                <label for="id_is_public">Публичный доступ</label>
                <input type="checkbox" id="id_is_public" ng-model="video.is_public"
                       ng-disabled="data.state!='send_form'">
              </div>
            </div>
            <div ng-if="data.state=='upload' || data.state=='progress'">
              <span ng-if="data.state=='upload'"><i class="fa fa-refresh fa-spin"></i> Загрузка видео ...</span>
              <span ng-if="data.state=='progress'"><i class="fa fa-refresh fa-spin"></i> Обработка видео ...</span>
              <div class="progress">
                <span class="progress-bar progress-bar-striped progress-bar-success"
                      style="width:{$ data.percent $}%;">{$ data.percent $}%</span>
              </div>
            </div>
            <div ng-if="data.error" class="alert alert-danger">{$ data.error $}</div>
          </div>
        </div>
        <div ng-if="data.state=='saved'">
          <div class="col-md-6">
            <div class="form-group">
              Видео сохранено и доступно по ссылке: <a href="/video/{$ data.video_id $}">http://ws.last-man.org/video/{$ data.video_id $}</a>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button ng-if="data.state=='send_form'||data.state=='set_link'"
                  type="button" class="btn btn-default" ng-click="reset()">Назад</button>
          <button ng-if="data.state=='send_form'"
                  type="button" class="btn btn-primary" ng-click="videoSave()">Сохранить</button>
        </div>
        <div class="clearfix"></div>
      </div><!-- /.modal-content -->
    </form>
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

videohub/templates/videohub/list.html
{% extends 'main/home.html' %}
{% load humanize %}
{% load staticfiles %}
{% load subdomain_urls %}

{% block title %}Список видео{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="{% static 'js/angular/angular.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/angular/angular-locale_ru-ru.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/dateformat.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/video_form.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/video_show.js' %}?2"></script>
  <script>
  var urls = {
    'api_video_get_progress': '{% url 'api_video_get_progress' 'api' %}',
    'api_video_save': '{% url 'api_video_save' 'api' %}',
    'api_video_info': '{% url 'api_video_info' 'api' %}',
    'api_video_show': '{% url 'api_video_show' 'api' %}',
    'api_video_exercise_list': '{% url 'api_video_exercise_list' 'api' %}',
  };
  angular.element(document).ready(function() {
    angular.bootstrap($('#video_show_modal'), ['showVideoApp']);
    angular.bootstrap($('#video_add_form'), ['addVideoApp']);
  });
  </script>
{% endblock %}

{% block content %}
  {% include 'videohub/add_form.html' %}
  {% include 'videohub/show_modal.html' %}

  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-md-12 well">
          <h3>Список видео</h3>
          {% if request.user.is_authenticated %}
            <button class="btn btn-success pull-right" onclick="showVideoForm()">
              <i class="fa fa-video-camera"></i>
              Добавить видео
            </button>
          {% endif %}
        </div>

        {% if objs %}
          {% for video in objs %}
            <div class="col-md-3 well">
              <a href="javascript:showVideo({{ video.id }});">
                <img src="https://i.ytimg.com/vi/{{ video.youtube_id }}/hqdefault.jpg" class="img-responsive">
              </a>
              <div>
                <a style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;display: block;"
                   href="javascript:showVideo({{ video.id }});"><b>{{ video.name }}</b></a>
                <a class="pull-right" href="{% url 'profile_show' 'ws' video.user.username %}">
                  <i class="fa fa-user"></i>&nbsp;{{ video.user.fullname }}

                <form method="POST" action="{% url 'video_delete' 'ws' video.id %}">
                  {% csrf_token %}
                  <a class="btn btn-danger pull-left btn-xs" onclick="if(confirm('Вы уверены?')){$(this).closest('form').submit()}">
                    <i class="fa fa-trash-o"></i> удалить
                  </a>
                </form>
              </div>
            </div>
          {% endfor %}
          {% include 'main/pagination.html' %}
        {% else %}
          <div class="alert alert-info">
            <i>пусто</i>
          </div>
        {% endif %}

      </div>
    </div>
  </div>
{% endblock %}

videohub/templates/videohub/show_modal.html
<div class="modal fade" id="video_show_modal" ng-app="showVideoApp" ng-controller="ShowVideoCtrl"
     tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Закрыть">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" style="text-align:center;">{$ data.title $}</h4>
      </div>
      <div ng-if="video" class="embed-responsive embed-responsive-16by9">
        <iframe type="text/html" class="embed-responsive-item" frameborder="0"
          ng-src="{$ getIframeSrc(video.youtube_id) $}"></iframe>
      </div>
      <div class="modal-body">
        <div ng-if="video" class="row">
          <div class="col-md-8">
            <div style="font-weight: 700;font-size: 120%;">{$ video.title $}</div>
            <div ng-if="video.description">{$ video.description $}</div>
            <small><i class="fa fa-link"></i>&nbsp; <a href="http://ws.last-man.org/video/{$ video.id $}/">http://ws.last-man.org/video/{$ video.id $}/</a></small>
          </div>
          <div class="col-md-4" style="text-align: right;">
            <div><i class="fa fa-eye"></i> {$ video.view_count $}</div>
            <div><i class="fa fa-user"></i>&nbsp;{$ video.user.fullname $}</div>
            <div>выполнено: {$ video.executed_at $}</div>
            <small ng-if="video.is_public"><i class="fa fa-users"></i>&nbsp;публичное</small>
            <small ng-if="!video.is_public"><i class="fa fa-lock"></i>&nbsp;личное</small>
          </div>
        </div>

      </div>
      <div class="clearfix"></div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->